; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = T-Call-A7670X-V1-1

[env]
platform = espressif32@6.9.0
framework = arduino
monitor_speed = 115200
src_filter = +<*.cpp> +<*.h>

[esp32dev_base]
board = esp32dev
build_flags = 
	${env.build_flags}
	-mfix-esp32-psram-cache-issue
	-DBOARD_HAS_PSRAM
monitor_filters = 
	default
	esp32_exception_decoder

[env:T-Call-A7670X-V1-1]
extends = esp32dev_base
build_flags = ${esp32dev_base.build_flags}
            -DLILYGO_T_CALL_A7670_V1_1
lib_deps = 
	vshymanskyy/StreamDebugger@^1.0.1
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson@^7.3.0

